SMY_ENV=DEV

DBGVIEW=*SOURCE

SHELL=/QOpenSys/usr/bin/qsh

BIN_LIB=TESTLIB

DTA_LIB=$(BIN_LIB)

SRC_LIB=$(BIN_LIB)

MBR_PGM=SOURCE

MBR_DDS=SOURCE

LIBLIST=$(BIN_LIB) QTEMP

all: sysvarr.sqlrpgle

# Daily sales person sales

# bidyspsls.pgm: bidyspsls.sqlrpglemod dlsspsrcd.sqlrpglemod

# bidyspsls.sqlrpglemod: bidyspslsd.dspf

# rpdlssps.pgm: rpdlssps.sqlrpglemod dlsspsrcd.sqlrpglemod

# rpdlssps.sqlrpglemod: rpdlsspsp.prtf asoscmv1

asoscmv1:

-db2 -t -f ./buildSrc/asoscmv1.sql $(DTA_LIB) | /usr/bin/iconv -t 819 -f 37;

system "CPYFRMSTMF FROMSTMF('./buildSrc/asoscmv1.sql') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_DDS).file/asoscmv1.mbr') MBROPT(*replace)"

%.rpgle:

liblist -d TESTLIB; \

liblist -al $(LIBLIST);\

system "CRTRPGMOD MODULE($(BIN_LIB)/$*) SRCSTMF('./src/qrpglesrc/$*.rpgle') DBGVIEW($(DBGVIEW)) REPLACE(*YES)"

system "CPYFRMSTMF FROMSTMF('./src/qrpglesrc/$*.rpgle') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_PGM).file/$*.mbr') MBROPT(*replace)"

%.c:

system "CRTCMOD MODULE($(BIN_LIB)/$*) SRCSTMF('./src/$*.c') DBGVIEW($(DBGVIEW)) REPLACE(*YES)"
%.clle:

#Can't compile CL from IFS on all OS versions... < 7.1

-system -q "CRTSRCPF FILE($(BIN_LIB)/$(MBR_PGM)) RCDLEN(112)"

system "CPYFRMSTMF FROMSTMF('./src/$*.clle') TOMBR('/QSYS.lib/$(BIN_LIB).lib/$(MBR_PGM).file/$*.mbr') MBROPT(*replace)"

system "CRTCLMOD MODULE($(BIN_LIB)/$*) SRCFILE($(BIN_LIB)/$(MBR_PGM)) DBGVIEW($(DBGVIEW))"

%.dspf:

liblist -d PROFSRVDEV; \

liblist -al $(LIBLIST); \

system "CPYFRMSTMF FROMSTMF('./src/qddssrc/$*.dspf') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_DDS).file/$*.mbr') MBROPT(*replace)"

system "CRTDSPF FILE($(BIN_LIB)/$*) SRCFILE($(SRC_LIB)/$(MBR_DDS)) SRCMBR($*) REPLACE(*YES)"

%.prtf:

liblist -d PROFSRVDEV; \

liblist -al $(LIBLIST); \

system "CPYFRMSTMF FROMSTMF('./src/qddssrc/$*.prtf') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_DDS).file/$*.mbr') MBROPT(*replace)"

system "CRTPRTF FILE($(BIN_LIB)/$*) SRCFILE($(SRC_LIB)/$(MBR_DDS)) SRCMBR($*) DEVTYPE(*AFPDS) IGCDTA(*N) IGCEXNCHR(*N) IGCCHRRTT(*N) IGCCPI(*N) IGCSOSI(*N) IGCCDEFNT(*SYSVAL) REPLACE(*YES) "

%.pgm:

liblist -d PROFSRVDEV; \

liblist -d PUIDEV;\

liblist -al $(LIBLIST);\

system "CRTPGM PGM($(BIN_LIB)/$*) MODULE($(patsubst %,$(BIN_LIB)/%,$(basename $^))) ENTMOD($(BIN_LIB)/$*) REPLACE(*YES)"

%.sqlrpglemod:

liblist -d PROFSRVDEV;\

liblist -d PUIDEV;\

liblist -al $(LIBLIST);\

system "CRTSQLRPGI OBJ($(BIN_LIB)/$*) SRCSTMF('./src/qrpglesrc/$*.sqlrpglemod') OBJTYPE(*MODULE) REPLACE(*YES)"

system "CPYFRMSTMF FROMSTMF('./src/qrpglesrc/$*.sqlrpglemod') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_PGM).file/$*.mbr') MBROPT(*replace)"

%.sqlrpgle:

liblist -d TESTLIB;\

# liblist -d PUIDEV;\
 liblist -al $(LIBLIST);\

system "CRTSQLRPGI OBJ($(BIN_LIB)/$*) SRCSTMF('./src/qrpglesrc/$*.sqlrpgle') OBJTYPE(*PGM) REPLACE(*YES)"

system "CPYFRMSTMF FROMSTMF('./src/qrpglesrc/$*.sqlrpgle') TOMBR('/QSYS.lib/$(SRC_LIB).lib/$(MBR_PGM).file/$*.mbr') MBROPT(*replace)"

%.sql:

sed -i.bak "s/DTA_LIB/$(DTA_LIB)/g" ./$*.sql

system "RUNSQLSTM SRCSTMF('./src/$*.sql')"

all:

@echo "Build finished!" 
